services:
  devenv:
    extends:
      file: docker-compose.base.yml
      service: devenv
    command: ["sleep", "infinity"]

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

volumes:
  postgres_data:
    driver: local
